serviceMonitor:
  targets:    # example
   - name: google              # Human readable URL that will appear in Prometheus / AlertManager
     url:  https://google.com

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"
