nginx:
  ingress:
    enabled: false
    ingressClassName: nginx
    hosts:
      - host: mimir.ref.stg.skaf.squareops.in
        paths:
          - path: /
            pathType: Prefix
    tls:
        # empty, disabled.

serviceMonitor:
  enabled: true
  interval: 10s
